stocks:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server' # (The ODBC Driver installed on your system)
      server: Anders_Desktop
      port: 1433
      database: Stocks
      schema: dbo
      user: dbt
      password: Warlordmanrock95
      trust_cert: True