stocks:
  target: stocks
  outputs:
    stocks:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server' # (The ODBC Driver installed on your system)
      server: localhost
      database: Stocks
      schema: dbo
      windows_login: True
      trust_cert: True