select "date" as date_reported, 
cast(SYMBOL as VARCHAR2(20)) as ticker, 
cast("reportedCurrency" as VARCHAR2(20)) as reported_currency, 
cast(CIK as number) as cik, 
cast(to_date(substr("fillingDate",1,10),'yyyy-mm-dd') as date) as fillingdate, 
cast(to_date(substr("acceptedDate",1,10),'yyyy-mm-dd') as date) as accepteddate, 
cast("calendarYear" as VARCHAR2(100)) as calendar_year, 
cast("PERIOD" as VARCHAR2(100)) as period, 
cast("netIncome" as number) as net_income, 
cast("depreciationAndAmortization" as number) as depreciation_and_amortization, 
cast("deferredIncomeTax" as number) as deferred_income_tax, 
cast("stockBasedCompensation" as number) as stock_based_compensation, 
cast("changeInWorkingCapital" as number) as change_in_working_capital, 
cast("accountsReceivables" as number) as accounts_receivables, 
cast("INVENTORY" as number) as inventory, 
cast("accountsPayables" as number) as accounts_payables, 
cast("otherWorkingCapital" as number) as other_working_capital, 
cast("otherNonCashItems" as VARCHAR2(100)) as other_non_cash_items, 
cast("netCashProvidedByOperatingActivites" as number) as net_cash_provided_by_operating_activities, 
cast("investmentsInPropertyPlantAndEquipment" as number) as investments_in_property_plant_and_equipment, 
cast("acquisitionsNet" as number) as acquisitions_net, 
cast("purchasesOfInvestments" as number) as purchases_of_investments, 
cast("salesMaturitiesOfInvestments" as number) as sales_maturities_of_investments, 
cast("otherInvestingActivites" as VARCHAR2(100)) as other_investing_activities, 
cast("netCashUsedForInvestingActivites" as number) as net_cash_used_for_investing_activities, 
cast("debtRepayment" as number) as debt_repayment, 
cast("commonStockIssued" as VARCHAR2(100)) as common_stock_issued, 
cast("commonStockRepurchased" as VARCHAR2(100)) as common_stock_repurchased, 
cast("dividendsPaid" as number) as dividends_paid, 
cast("otherFinancingActivites" as VARCHAR2(100)) as other_financing_activities, 
cast("netCashUsedProvidedByFinancingActivities" as number) as net_cash_used_provided_by_financing_activities, 
cast("effectOfForexChangesOnCash" as VARCHAR2(100)) as effect_of_forex_changes_on_cash, 
cast("netChangeInCash" as number) as net_change_in_cash, 
cast("cashAtEndOfPeriod" as number) as cash_at_end_of_period, 
cast("cashAtBeginningOfPeriod" as number) as cash_at_beginning_of_period, 
cast("operatingCashFlow" as number) as operating_cash_flow, 
cast("capitalExpenditure" as number) as capital_expenditure, 
cast("freeCashFlow" as number) as free_cash_flow,
link, 
"finalLink" as finallink

from 
{{source('STOCK_IMPORT','IM_CASH_FLOW_BULK_QUARTER')}} 
