select 
date, 
cast(SYMBOL as number) as, 
cast("reportedCurrency" as number) as reported_currency, 
cast(CIK as number) as cik, 
fillingDate, 
acceptedDate, 
calendarYear, 
PERIOD, 
netIncome, 
depreciationAndAmortization, 
deferredIncomeTax, 
stockBasedCompensation, 
changeInWorkingCapital, 
accountsReceivables, 
INVENTORY, 
accountsPayables, 
otherWorkingCapital, 
otherNonCashItems, 
netCashProvidedByOperatingActivites, 
investmentsInPropertyPlantAndEquipment, 
acquisitionsNet, 
purchasesOfInvestments, 
salesMaturitiesOfInvestments, 
otherInvestingActivites, 
netCashUsedForInvestingActivites, 
debtRepayment, 
commonStockIssued, 
commonStockRepurchased, 
dividendsPaid, 
otherFinancingActivites, 
netCashUsedProvidedByFinancingActivities, 
effectOfForexChangesOnCash, 
netChangeInCash, 
cashAtEndOfPeriod, 
cashAtBeginningOfPeriod, 
operatingCashFlow, 
capitalExpenditure, 
freeCashFlow, 
LINK, 
finalLink 
from 
STOCK_IMPORT.IM_CASH_FLOW_BULK_ANNUAL t