select  
cast(symbol as VARCHAR2(20)) as ticker,
cast("reportedCurrency" as VARCHAR2(20)) as reported_currency,
cast(cik as VARCHAR2(20)) as cik ,
cast(to_date("fillingDate",'yyyy-mm-dd') as date) as filling_date, 
cast(to_date(substr("acceptedDate",1,10),'yyyy-mm-dd') as date) as accepted_date,
cast("calendarYear" as VARCHAR2(4)) as calendar_year,
cast(period as VARCHAR2(2)) as period,
cast(REVENUE as number) as REVENUE,
cast("costOfRevenue" as number) as costOf_revenue,
cast("grossProfit" as number) as gross_profit,
"grossProfitRatio",
cast("ResearchAndDevelopmentExpenses" as number) as research_and_development_expenses,
cast("GeneralAndAdministrativeExpenses" as number) as general_and_administrative_expenses,
cast("SellingAndMarketingExpenses" as number) as selling_and_marketing_expenses,
cast("SellingGeneralAndAdministrativeExpenses" as number) as selling_general_and_administrativ_expenses, 
cast("otherExpenses" as number) as other_expenses,
cast("operatingExpenses" as number) as operating_expenses,
cast("costAndExpenses" as number) as cost_and_expenses,
cast("interestExpense" as number) as interest_expense,
cast("depreciationAndAmortization" as number) as depreciation_and_amortization, 
cast(ebitda as number) as ebitda, 
"EBITDARatio",
cast("operatingIncome" as number) operating_income,
"operatingIncomeRatio",
cast("totalOtherIncomeExpensesNet" as number) as total_other_income_expenses_net, 
cast("incomeBeforeTax" as number) as income_before_tax, 
"incomeBeforeTaxRatio",
cast("incomeTaxExpense" as number) as income_tax_expense,
cast("netIncome" as number) as  net_income, 
"netIncomeRatio", 
cast(eps as number) as eps,
cast("EPSDiluted" as number) as eps_diluted, 
cast("weightedAverageShsOut" as number) as weighted_average_shs_out, 
cast("weightedAverageShsOutDil" as number) as weighted_average_shs_out_dil, 
link, 
"finalLink" 
from  {{source('STOCK_IMPORT','IM_INCOME_STATEMENT_BULK_ANNUAL')}} 