SELECT
    CAST(SYMBOL AS varchar2(20)) as symbol,
  cast(to_date(substr("date",1,10),'yyyy-mm-dd') as date) as date_sent,
    CAST(PERIOD AS varchar2(20)) as period,
    ROUND(CAST("currentRatio" AS NUMBER), 3) as current_ratio,
    ROUND(CAST("quickRatio" AS NUMBER), 3) as quick_ratio,
    ROUND(CAST("cashRatio" AS NUMBER), 3) as cash_ratio,
    ROUND(CAST("daysOfSalesOutstanding" AS NUMBER), 3) as days_of_sales_outstanding,
    ROUND(CAST("daysOfInventoryOutstanding" AS NUMBER), 3) as days_of_inventory_outstanding,
    ROUND(CAST("operatingCycle" AS NUMBER), 3) as operating_cycle,
    ROUND(CAST("daysOfPayablesOutstanding" AS NUMBER), 3) as days_of_payables_outstanding,
    ROUND(CAST("cashConversionCycle" AS NUMBER), 3) as cash_conversion_cycle,
    ROUND(CAST("grossProfitMargin" AS NUMBER), 3) as gross_profit_margin,
    ROUND(CAST("operatingProfitMargin" AS NUMBER), 3) as operating_profit_margin,
    ROUND(CAST("pretaxProfitMargin" AS NUMBER), 3) as pretax_profit_margin,
    ROUND(CAST("netProfitMargin" AS NUMBER), 3) as net_profit_margin,
    ROUND(CAST("effectiveTaxRate" AS NUMBER), 3) as effective_tax_rate,
    ROUND(CAST("returnOnAssets" AS NUMBER), 3) as return_on_assets,
    ROUND(CAST("returnOnEquity" AS NUMBER), 3) as return_on_equity,
    ROUND(CAST("returnOnCapitalEmployed" AS NUMBER), 3) as return_on_capital_employed,
    ROUND(CAST("netIncomePerEBT" AS NUMBER), 3) as net_income_per_ebt,
    ROUND(CAST("ebtPerEbit" AS NUMBER), 3) as ebt_per_ebit,
    ROUND(CAST("ebitPerRevenue" AS NUMBER), 3) as ebit_per_revenue,
    ROUND(CAST("debtRatio" AS NUMBER), 3) as debt_ratio,
    ROUND(CAST("debtEquityRatio" AS NUMBER), 3) as debt_equity_ratio,
    ROUND(CAST("longTermDebtToCapitalization" AS NUMBER), 3) as long_term_debt_to_capitalization,
    ROUND(CAST("totalDebtToCapitalization" AS NUMBER), 3) as total_debt_to_capitalization,
    ROUND(CAST("interestCoverage" AS NUMBER), 3) as interest_coverage,
    ROUND(CAST("cashFlowToDebtRatio" AS NUMBER), 3) as cash_flow_to_debt_ratio,
    ROUND(CAST("companyEquityMultiplier" AS NUMBER), 3) as company_equity_multiplier,
    ROUND(CAST("receivablesTurnover" AS NUMBER), 3) as receivables_turnover,
    ROUND(CAST("payablesTurnover" AS NUMBER), 3) as payables_turnover,
    ROUND(CAST("inventoryTurnover" AS NUMBER), 3) as inventory_turnover,
    ROUND(CAST("fixedAssetTurnover" AS NUMBER), 3) as fixed_asset_turnover,
    ROUND(CAST("assetTurnover" AS NUMBER), 3) as asset_turnover,
    ROUND(CAST("operatingCashFlowPerShare" AS NUMBER), 3) as operating_cash_flow_per_share,
    ROUND(CAST("freeCashFlowPerShare" AS NUMBER), 3) as free_cash_flow_per_share,
    ROUND(CAST("cashPerShare" AS NUMBER), 3) as cash_per_share,
    ROUND(CAST("payoutRatio" AS NUMBER), 3) as payout_ratio,
    ROUND(CAST("operatingCashFlowSalesRatio" AS NUMBER), 3) as operating_cash_flow_sales_ratio,
    ROUND(CAST("freeCashFlowOperatingCashFlowRatio" AS NUMBER), 3) as free_cash_flow_operating_cash_flow_ratio,
    ROUND(CAST("cashFlowCoverageRatios" AS NUMBER), 3) as cash_flow_coverage_ratios,
    ROUND(CAST("shortTermCoverageRatios" AS NUMBER), 3) as short_term_coverage_ratios,
    ROUND(CAST("capitalExpenditureCoverageRatio" AS NUMBER), 3) as capital_expenditure_coverage_ratio,
    ROUND(CAST("dividendPaidAndCapexCoverageRatio" AS NUMBER), 3) as dividend_paid_and_capex_coverage_ratio,
    ROUND(CAST("dividendPayoutRatio" AS NUMBER), 3) as dividend_payout_ratio,
    ROUND(CAST("priceBookValueRatio" AS NUMBER), 3) as price_book_value_ratio,
    ROUND(CAST("priceToBookRatio" AS NUMBER), 3) as price_to_book_ratio,
    ROUND(CAST("priceToSalesRatio" AS NUMBER), 3) as price_to_sales_ratio,
    ROUND(CAST("priceEarningsRatio" AS NUMBER), 3) as price_earnings_ratio,
    ROUND(CAST("priceToFreeCashFlowsRatio" AS NUMBER), 3) as price_to_free_cash_flows_ratio,
    ROUND(CAST("priceToOperatingCashFlowsRatio" AS NUMBER), 3) as price_to_operating_cash_flows_ratio,
    ROUND(CAST("priceCashFlowRatio" AS NUMBER), 3) as price_cash_flow_ratio,
    ROUND(CAST("priceEarningsToGrowthRatio" AS NUMBER), 3) as price_earnings_to_growth_ratio,
    ROUND(CAST("priceSalesRatio" AS NUMBER), 3) as price_sales_ratio,
    ROUND(CAST("dividendYield" AS NUMBER), 3) as dividend_yield,
    ROUND(CAST("enterpriseValueMultiple" AS NUMBER), 3) as enterprise_value_multiple,
    ROUND(CAST("priceFairValue" AS NUMBER), 3) as price_fair_value
FROM
{{source('STOCK_IMPORT','IM_RATIOS_BULK_ANNUAL')}} 
    
